### ISSUE TITLE
baseline error

### ISSUE THREAD

**Issue by nodegin** [max32002/swei-gothic#1]
<img width="211" alt="Screenshot 2020-05-12 at 7 57 13 PM" src="https://user-images.githubusercontent.com/8536244/81685859-d0574780-948a-11ea-8f7f-7a4f693c223e.png">

**Comment by max32002** [comment]
方便打中文嗎？你的問題無法理解，太技術。

**Comment by max32002** [comment]
主因是因為拔腳，造成的懸空。
![Screen Shot 2020-05-12 at 20 37 54](https://user-images.githubusercontent.com/4498233/81692163-8b361400-9490-11ea-8ba4-f0521cfb51ba.png)

**Comment by max32002** [comment]
![Screen Shot 2020-05-21 at 22 46 26](https://user-images.githubusercontent.com/4498233/82571036-f67c9600-9bb4-11ea-88dd-f7fe0f569f5e.png)
# 2020/05/21 ver 1.028
* 修正baseline inconsistant(拔腳後懸空)問題。

**Comment by nodegin** [comment]
最新版本 (2.054) 再次出現

<img width="400" alt="Screenshot 2020-06-24 at 1 26 04 AM" src="https://user-images.githubusercontent.com/8536244/85435205-b183bf00-b5b9-11ea-8254-6212ae4c7bf0.png">
<img width="151" alt="Screenshot 2020-06-24 at 1 26 16 AM" src="https://user-images.githubusercontent.com/8536244/85435244-bea0ae00-b5b9-11ea-8efb-26ceb1ba809c.png">

**Comment by max32002** [comment]
這次的比較難解。程式的部分暫時沒有想到解法。

使用純手工調整一下，應該會比寫程式簡單。


「雅」字右邊也因為拔腳而懸空了。

**Comment by max32002** [comment]
你的版本，好像怪怪的，你的「台」跟我的版本不一樣。
![Screen Shot 2020-06-24 at 07 00 56](https://user-images.githubusercontent.com/4498233/85475754-2cb09980-b5e9-11ea-820c-176347f05dba.png)

**Comment by max32002** [comment]
解決了，請重新下載 ver 2.060
![Screen Shot 2020-06-24 at 22 28 45](https://user-images.githubusercontent.com/4498233/85575779-6c6b9580-b66a-11ea-85c9-7d095acd30ef.png)

**Comment by nodegin** [comment]
感謝

**Comment by max32002** [comment]
附註：ver 2.060 似乎有掉了很多字，可能是因為修改了字型檔案的 namelist 屬性又同時更新部份內容造成錯誤。已修正掉字問題在 ver 2.061.
