### ISSUE TITLE
獅尾圓體和台灣圓體的區別

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [max32002/swei-gothic#2]
獅尾圓體和台灣圓體都是思源黑體改造的，但有什麼不同？

**Comment by max32002** [comment]
台灣圓體，有些字來自小杉圓體。

**Comment by UltimateAmitieKaiNiC** [comment]
不如對比一下

**Comment by UltimateAmitieKaiNiC** [comment]
不如台灣圓體和獅尾圓體來對比一下

**Comment by max32002** [comment]
<img width="1214" alt="Screen Shot 2020-07-05 at 22 46 07" src="https://user-images.githubusercontent.com/4498233/86535281-d2310a80-bf11-11ea-83dd-43b0db27b487.png">
* 圖片裡上半部是台灣圓體，有補一些不常用字，有些字是套用小杉的字。

* 圖片裡下半部是獅尾圓體，最後二行字，因為缺字所以字型跑掉，有些變成莫大書法字體，最後幾個字，系統幫我選擇使用粉圓字體來顯示。

其實台灣圓體是也可以完全不使用小杉，變成針對那些直接用小杉的字需要多花一點點時間去修改字體。

**Comment by UltimateAmitieKaiNiC** [comment]
但是邋字的辶部仍舊是舊版本

**Comment by max32002** [comment]
好眼力！改天再來更新一下使用新的辵部。

**Comment by max32002** [comment]
台灣圓體ver 2.063調整：西、邋、鼹。
